#include <kan/error/critical.h>
#include <kan/platform/conversion.h>

enum kan_platform_window_flag_t to_kan_window_flags (uint64_t sdl_flags)
{
    enum kan_platform_window_flag_t flags = 0u;
#define CHECK_FLAGS(KAN_FLAG, SDL_FLAG)                                                                                \
    if (sdl_flags & SDL_FLAG)                                                                                          \
    {                                                                                                                  \
        flags |= KAN_FLAG;                                                                                             \
    }

    CHECK_FLAGS (KAN_PLATFORM_WINDOW_FLAG_FULLSCREEN, SDL_WINDOW_FULLSCREEN)
    CHECK_FLAGS (KAN_PLATFORM_WINDOW_FLAG_SUPPORTS_OPEN_GL, SDL_WINDOW_OPENGL)
    CHECK_FLAGS (KAN_PLATFORM_WINDOW_FLAG_SUPPORTS_VULKAN, SDL_WINDOW_VULKAN)
    CHECK_FLAGS (KAN_PLATFORM_WINDOW_FLAG_SUPPORTS_METAL, SDL_WINDOW_METAL)
    CHECK_FLAGS (KAN_PLATFORM_WINDOW_FLAG_OCCLUDED, SDL_WINDOW_OCCLUDED)
    CHECK_FLAGS (KAN_PLATFORM_WINDOW_FLAG_HIDDEN, SDL_WINDOW_HIDDEN)
    CHECK_FLAGS (KAN_PLATFORM_WINDOW_FLAG_BORDERLESS, SDL_WINDOW_BORDERLESS)
    CHECK_FLAGS (KAN_PLATFORM_WINDOW_FLAG_TRANSPARENT, SDL_WINDOW_TRANSPARENT)
    CHECK_FLAGS (KAN_PLATFORM_WINDOW_FLAG_RESIZABLE, SDL_WINDOW_RESIZABLE)
    CHECK_FLAGS (KAN_PLATFORM_WINDOW_FLAG_MINIMIZED, SDL_WINDOW_MINIMIZED)
    CHECK_FLAGS (KAN_PLATFORM_WINDOW_FLAG_MAXIMIZED, SDL_WINDOW_MAXIMIZED)
    CHECK_FLAGS (KAN_PLATFORM_WINDOW_FLAG_UTILITY, SDL_WINDOW_UTILITY)
    CHECK_FLAGS (KAN_PLATFORM_WINDOW_FLAG_TOOLTIP, SDL_WINDOW_TOOLTIP)
    CHECK_FLAGS (KAN_PLATFORM_WINDOW_FLAG_POPUP, SDL_WINDOW_POPUP_MENU)
    CHECK_FLAGS (KAN_PLATFORM_WINDOW_FLAG_ALWAYS_ON_TOP, SDL_WINDOW_ALWAYS_ON_TOP)
    CHECK_FLAGS (KAN_PLATFORM_WINDOW_FLAG_HIGH_PIXEL_DENSITY, SDL_WINDOW_HIGH_PIXEL_DENSITY)
    CHECK_FLAGS (KAN_PLATFORM_WINDOW_FLAG_MOUSE_GRABBED, SDL_WINDOW_MOUSE_GRABBED)
    CHECK_FLAGS (KAN_PLATFORM_WINDOW_FLAG_KEYBOARD_GRABBED, SDL_WINDOW_KEYBOARD_GRABBED)
    CHECK_FLAGS (KAN_PLATFORM_WINDOW_FLAG_INPUT_FOCUS, SDL_WINDOW_INPUT_FOCUS)
    CHECK_FLAGS (KAN_PLATFORM_WINDOW_FLAG_MOUSE_FOCUS, SDL_WINDOW_MOUSE_FOCUS)
    CHECK_FLAGS (KAN_PLATFORM_WINDOW_FLAG_MOUSE_CAPTURE, SDL_WINDOW_MOUSE_CAPTURE)
#undef CHECK_FLAGS
    return flags;
}

uint32_t to_sdl_window_flags (enum kan_platform_window_flag_t flags)
{
    uint32_t sdl_flags = 0u;
#define CHECK_FLAGS(KAN_FLAG, SDL_FLAG)                                                                                \
    if (flags & KAN_FLAG)                                                                                              \
    {                                                                                                                  \
        sdl_flags |= SDL_FLAG;                                                                                         \
    }

    CHECK_FLAGS (KAN_PLATFORM_WINDOW_FLAG_FULLSCREEN, SDL_WINDOW_FULLSCREEN)
    CHECK_FLAGS (KAN_PLATFORM_WINDOW_FLAG_SUPPORTS_OPEN_GL, SDL_WINDOW_OPENGL)
    CHECK_FLAGS (KAN_PLATFORM_WINDOW_FLAG_SUPPORTS_VULKAN, SDL_WINDOW_VULKAN)
    CHECK_FLAGS (KAN_PLATFORM_WINDOW_FLAG_SUPPORTS_METAL, SDL_WINDOW_METAL)
    CHECK_FLAGS (KAN_PLATFORM_WINDOW_FLAG_OCCLUDED, SDL_WINDOW_OCCLUDED)
    CHECK_FLAGS (KAN_PLATFORM_WINDOW_FLAG_HIDDEN, SDL_WINDOW_HIDDEN)
    CHECK_FLAGS (KAN_PLATFORM_WINDOW_FLAG_BORDERLESS, SDL_WINDOW_BORDERLESS)
    CHECK_FLAGS (KAN_PLATFORM_WINDOW_FLAG_TRANSPARENT, SDL_WINDOW_TRANSPARENT)
    CHECK_FLAGS (KAN_PLATFORM_WINDOW_FLAG_RESIZABLE, SDL_WINDOW_RESIZABLE)
    CHECK_FLAGS (KAN_PLATFORM_WINDOW_FLAG_MINIMIZED, SDL_WINDOW_MINIMIZED)
    CHECK_FLAGS (KAN_PLATFORM_WINDOW_FLAG_MAXIMIZED, SDL_WINDOW_MAXIMIZED)
    CHECK_FLAGS (KAN_PLATFORM_WINDOW_FLAG_UTILITY, SDL_WINDOW_UTILITY)
    CHECK_FLAGS (KAN_PLATFORM_WINDOW_FLAG_TOOLTIP, SDL_WINDOW_TOOLTIP)
    CHECK_FLAGS (KAN_PLATFORM_WINDOW_FLAG_POPUP, SDL_WINDOW_POPUP_MENU)
    CHECK_FLAGS (KAN_PLATFORM_WINDOW_FLAG_ALWAYS_ON_TOP, SDL_WINDOW_ALWAYS_ON_TOP)
    CHECK_FLAGS (KAN_PLATFORM_WINDOW_FLAG_HIGH_PIXEL_DENSITY, SDL_WINDOW_HIGH_PIXEL_DENSITY)
    CHECK_FLAGS (KAN_PLATFORM_WINDOW_FLAG_MOUSE_GRABBED, SDL_WINDOW_MOUSE_GRABBED)
    CHECK_FLAGS (KAN_PLATFORM_WINDOW_FLAG_KEYBOARD_GRABBED, SDL_WINDOW_KEYBOARD_GRABBED)
    CHECK_FLAGS (KAN_PLATFORM_WINDOW_FLAG_INPUT_FOCUS, SDL_WINDOW_INPUT_FOCUS)
    CHECK_FLAGS (KAN_PLATFORM_WINDOW_FLAG_MOUSE_FOCUS, SDL_WINDOW_MOUSE_FOCUS)
    CHECK_FLAGS (KAN_PLATFORM_WINDOW_FLAG_MOUSE_CAPTURE, SDL_WINDOW_MOUSE_CAPTURE)
#undef CHECK_FLAGS
    return sdl_flags;
}

enum kan_platform_scan_code_t to_kan_scan_code (SDL_Scancode scan_code)
{
    switch (scan_code)
    {
    case SDL_SCANCODE_A:
        return KAN_PLATFORM_SCAN_CODE_A;
    case SDL_SCANCODE_B:
        return KAN_PLATFORM_SCAN_CODE_B;
    case SDL_SCANCODE_C:
        return KAN_PLATFORM_SCAN_CODE_C;
    case SDL_SCANCODE_D:
        return KAN_PLATFORM_SCAN_CODE_D;
    case SDL_SCANCODE_E:
        return KAN_PLATFORM_SCAN_CODE_E;
    case SDL_SCANCODE_F:
        return KAN_PLATFORM_SCAN_CODE_F;
    case SDL_SCANCODE_G:
        return KAN_PLATFORM_SCAN_CODE_G;
    case SDL_SCANCODE_H:
        return KAN_PLATFORM_SCAN_CODE_H;
    case SDL_SCANCODE_I:
        return KAN_PLATFORM_SCAN_CODE_I;
    case SDL_SCANCODE_J:
        return KAN_PLATFORM_SCAN_CODE_J;
    case SDL_SCANCODE_K:
        return KAN_PLATFORM_SCAN_CODE_K;
    case SDL_SCANCODE_L:
        return KAN_PLATFORM_SCAN_CODE_L;
    case SDL_SCANCODE_M:
        return KAN_PLATFORM_SCAN_CODE_M;
    case SDL_SCANCODE_N:
        return KAN_PLATFORM_SCAN_CODE_N;
    case SDL_SCANCODE_O:
        return KAN_PLATFORM_SCAN_CODE_O;
    case SDL_SCANCODE_P:
        return KAN_PLATFORM_SCAN_CODE_P;
    case SDL_SCANCODE_Q:
        return KAN_PLATFORM_SCAN_CODE_Q;
    case SDL_SCANCODE_R:
        return KAN_PLATFORM_SCAN_CODE_R;
    case SDL_SCANCODE_S:
        return KAN_PLATFORM_SCAN_CODE_S;
    case SDL_SCANCODE_T:
        return KAN_PLATFORM_SCAN_CODE_T;
    case SDL_SCANCODE_U:
        return KAN_PLATFORM_SCAN_CODE_U;
    case SDL_SCANCODE_V:
        return KAN_PLATFORM_SCAN_CODE_V;
    case SDL_SCANCODE_W:
        return KAN_PLATFORM_SCAN_CODE_W;
    case SDL_SCANCODE_X:
        return KAN_PLATFORM_SCAN_CODE_X;
    case SDL_SCANCODE_Y:
        return KAN_PLATFORM_SCAN_CODE_Y;
    case SDL_SCANCODE_Z:
        return KAN_PLATFORM_SCAN_CODE_Z;
    case SDL_SCANCODE_1:
        return KAN_PLATFORM_SCAN_CODE_1;
    case SDL_SCANCODE_2:
        return KAN_PLATFORM_SCAN_CODE_2;
    case SDL_SCANCODE_3:
        return KAN_PLATFORM_SCAN_CODE_3;
    case SDL_SCANCODE_4:
        return KAN_PLATFORM_SCAN_CODE_4;
    case SDL_SCANCODE_5:
        return KAN_PLATFORM_SCAN_CODE_5;
    case SDL_SCANCODE_6:
        return KAN_PLATFORM_SCAN_CODE_6;
    case SDL_SCANCODE_7:
        return KAN_PLATFORM_SCAN_CODE_7;
    case SDL_SCANCODE_8:
        return KAN_PLATFORM_SCAN_CODE_8;
    case SDL_SCANCODE_9:
        return KAN_PLATFORM_SCAN_CODE_9;
    case SDL_SCANCODE_0:
        return KAN_PLATFORM_SCAN_CODE_0;
    case SDL_SCANCODE_RETURN:
        return KAN_PLATFORM_SCAN_CODE_ENTER;
    case SDL_SCANCODE_ESCAPE:
        return KAN_PLATFORM_SCAN_CODE_ESCAPE;
    case SDL_SCANCODE_BACKSPACE:
        return KAN_PLATFORM_SCAN_CODE_BACKSPACE;
    case SDL_SCANCODE_TAB:
        return KAN_PLATFORM_SCAN_CODE_TAB;
    case SDL_SCANCODE_SPACE:
        return KAN_PLATFORM_SCAN_CODE_SPACE;
    case SDL_SCANCODE_MINUS:
        return KAN_PLATFORM_SCAN_CODE_MINUS;
    case SDL_SCANCODE_EQUALS:
        return KAN_PLATFORM_SCAN_CODE_EQUAL;
    case SDL_SCANCODE_LEFTBRACKET:
        return KAN_PLATFORM_SCAN_CODE_LEFT_BRACKET;
    case SDL_SCANCODE_RIGHTBRACKET:
        return KAN_PLATFORM_SCAN_CODE_RIGHT_BRACKET;
    case SDL_SCANCODE_BACKSLASH:
        return KAN_PLATFORM_SCAN_CODE_BACKSLASH;
    case SDL_SCANCODE_NONUSHASH:
        return KAN_PLATFORM_SCAN_CODE_NONUS_HASH;
    case SDL_SCANCODE_SEMICOLON:
        return KAN_PLATFORM_SCAN_CODE_SEMICOLON;
    case SDL_SCANCODE_APOSTROPHE:
        return KAN_PLATFORM_SCAN_CODE_APOSTROPHE;
    case SDL_SCANCODE_GRAVE:
        return KAN_PLATFORM_SCAN_CODE_GRAVE;
    case SDL_SCANCODE_COMMA:
        return KAN_PLATFORM_SCAN_CODE_COMMA;
    case SDL_SCANCODE_PERIOD:
        return KAN_PLATFORM_SCAN_CODE_PERIOD;
    case SDL_SCANCODE_SLASH:
        return KAN_PLATFORM_SCAN_CODE_SLASH;
    case SDL_SCANCODE_CAPSLOCK:
        return KAN_PLATFORM_SCAN_CODE_CAPSLOCK;
    case SDL_SCANCODE_F1:
        return KAN_PLATFORM_SCAN_CODE_F1;
    case SDL_SCANCODE_F2:
        return KAN_PLATFORM_SCAN_CODE_F2;
    case SDL_SCANCODE_F3:
        return KAN_PLATFORM_SCAN_CODE_F3;
    case SDL_SCANCODE_F4:
        return KAN_PLATFORM_SCAN_CODE_F4;
    case SDL_SCANCODE_F5:
        return KAN_PLATFORM_SCAN_CODE_F5;
    case SDL_SCANCODE_F6:
        return KAN_PLATFORM_SCAN_CODE_F6;
    case SDL_SCANCODE_F7:
        return KAN_PLATFORM_SCAN_CODE_F7;
    case SDL_SCANCODE_F8:
        return KAN_PLATFORM_SCAN_CODE_F8;
    case SDL_SCANCODE_F9:
        return KAN_PLATFORM_SCAN_CODE_F9;
    case SDL_SCANCODE_F10:
        return KAN_PLATFORM_SCAN_CODE_F10;
    case SDL_SCANCODE_F11:
        return KAN_PLATFORM_SCAN_CODE_F11;
    case SDL_SCANCODE_F12:
        return KAN_PLATFORM_SCAN_CODE_F12;
    case SDL_SCANCODE_PRINTSCREEN:
        return KAN_PLATFORM_SCAN_CODE_PRINT_SCREEN;
    case SDL_SCANCODE_SCROLLLOCK:
        return KAN_PLATFORM_SCAN_CODE_SCROLL_LOCK;
    case SDL_SCANCODE_PAUSE:
        return KAN_PLATFORM_SCAN_CODE_PAUSE;
    case SDL_SCANCODE_INSERT:
        return KAN_PLATFORM_SCAN_CODE_INSERT;
    case SDL_SCANCODE_HOME:
        return KAN_PLATFORM_SCAN_CODE_HOME;
    case SDL_SCANCODE_PAGEUP:
        return KAN_PLATFORM_SCAN_CODE_PAGE_UP;
    case SDL_SCANCODE_DELETE:
        return KAN_PLATFORM_SCAN_CODE_DELETE;
    case SDL_SCANCODE_END:
        return KAN_PLATFORM_SCAN_CODE_END;
    case SDL_SCANCODE_PAGEDOWN:
        return KAN_PLATFORM_SCAN_CODE_PAGE_DOWN;
    case SDL_SCANCODE_RIGHT:
        return KAN_PLATFORM_SCAN_CODE_RIGHT;
    case SDL_SCANCODE_LEFT:
        return KAN_PLATFORM_SCAN_CODE_LEFT;
    case SDL_SCANCODE_DOWN:
        return KAN_PLATFORM_SCAN_CODE_DOWN;
    case SDL_SCANCODE_UP:
        return KAN_PLATFORM_SCAN_CODE_UP;
    case SDL_SCANCODE_NUMLOCKCLEAR:
        return KAN_PLATFORM_SCAN_CODE_NUM_LOCK;
    case SDL_SCANCODE_KP_DIVIDE:
        return KAN_PLATFORM_SCAN_CODE_KEY_PAD_DIVIDE;
    case SDL_SCANCODE_KP_MULTIPLY:
        return KAN_PLATFORM_SCAN_CODE_KEY_PAD_MULTIPLY;
    case SDL_SCANCODE_KP_MINUS:
        return KAN_PLATFORM_SCAN_CODE_KEY_PAD_MINUS;
    case SDL_SCANCODE_KP_PLUS:
        return KAN_PLATFORM_SCAN_CODE_KEY_PAD_PLUS;
    case SDL_SCANCODE_KP_ENTER:
        return KAN_PLATFORM_SCAN_CODE_KEY_PAD_ENTER;
    case SDL_SCANCODE_KP_1:
        return KAN_PLATFORM_SCAN_CODE_KEY_PAD_1;
    case SDL_SCANCODE_KP_2:
        return KAN_PLATFORM_SCAN_CODE_KEY_PAD_2;
    case SDL_SCANCODE_KP_3:
        return KAN_PLATFORM_SCAN_CODE_KEY_PAD_3;
    case SDL_SCANCODE_KP_4:
        return KAN_PLATFORM_SCAN_CODE_KEY_PAD_4;
    case SDL_SCANCODE_KP_5:
        return KAN_PLATFORM_SCAN_CODE_KEY_PAD_5;
    case SDL_SCANCODE_KP_6:
        return KAN_PLATFORM_SCAN_CODE_KEY_PAD_6;
    case SDL_SCANCODE_KP_7:
        return KAN_PLATFORM_SCAN_CODE_KEY_PAD_7;
    case SDL_SCANCODE_KP_8:
        return KAN_PLATFORM_SCAN_CODE_KEY_PAD_8;
    case SDL_SCANCODE_KP_9:
        return KAN_PLATFORM_SCAN_CODE_KEY_PAD_9;
    case SDL_SCANCODE_KP_0:
        return KAN_PLATFORM_SCAN_CODE_KEY_PAD_0;
    case SDL_SCANCODE_KP_PERIOD:
        return KAN_PLATFORM_SCAN_CODE_KEY_PAD_PERIOD;
    case SDL_SCANCODE_NONUSBACKSLASH:
        return KAN_PLATFORM_SCAN_CODE_NONUS_BACKSLASH;
    case SDL_SCANCODE_APPLICATION:
        return KAN_PLATFORM_SCAN_CODE_APPLICATION;
    case SDL_SCANCODE_POWER:
        return KAN_PLATFORM_SCAN_CODE_POWER;
    case SDL_SCANCODE_KP_EQUALS:
        return KAN_PLATFORM_SCAN_CODE_KEY_PAD_EQUALS;
    case SDL_SCANCODE_F13:
        return KAN_PLATFORM_SCAN_CODE_F13;
    case SDL_SCANCODE_F14:
        return KAN_PLATFORM_SCAN_CODE_F14;
    case SDL_SCANCODE_F15:
        return KAN_PLATFORM_SCAN_CODE_F15;
    case SDL_SCANCODE_F16:
        return KAN_PLATFORM_SCAN_CODE_F16;
    case SDL_SCANCODE_F17:
        return KAN_PLATFORM_SCAN_CODE_F17;
    case SDL_SCANCODE_F18:
        return KAN_PLATFORM_SCAN_CODE_F18;
    case SDL_SCANCODE_F19:
        return KAN_PLATFORM_SCAN_CODE_F19;
    case SDL_SCANCODE_F20:
        return KAN_PLATFORM_SCAN_CODE_F20;
    case SDL_SCANCODE_F21:
        return KAN_PLATFORM_SCAN_CODE_F21;
    case SDL_SCANCODE_F22:
        return KAN_PLATFORM_SCAN_CODE_F22;
    case SDL_SCANCODE_F23:
        return KAN_PLATFORM_SCAN_CODE_F23;
    case SDL_SCANCODE_F24:
        return KAN_PLATFORM_SCAN_CODE_F24;
    case SDL_SCANCODE_EXECUTE:
        return KAN_PLATFORM_SCAN_CODE_EXECUTE;
    case SDL_SCANCODE_HELP:
        return KAN_PLATFORM_SCAN_CODE_HELP;
    case SDL_SCANCODE_MENU:
        return KAN_PLATFORM_SCAN_CODE_MENU;
    case SDL_SCANCODE_SELECT:
        return KAN_PLATFORM_SCAN_CODE_SELECT;
    case SDL_SCANCODE_STOP:
        return KAN_PLATFORM_SCAN_CODE_STOP;
    case SDL_SCANCODE_AGAIN:
        return KAN_PLATFORM_SCAN_CODE_AGAIN;
    case SDL_SCANCODE_UNDO:
        return KAN_PLATFORM_SCAN_CODE_UNDO;
    case SDL_SCANCODE_CUT:
        return KAN_PLATFORM_SCAN_CODE_CUT;
    case SDL_SCANCODE_COPY:
        return KAN_PLATFORM_SCAN_CODE_COPY;
    case SDL_SCANCODE_PASTE:
        return KAN_PLATFORM_SCAN_CODE_PASTE;
    case SDL_SCANCODE_FIND:
        return KAN_PLATFORM_SCAN_CODE_FIND;
    case SDL_SCANCODE_MUTE:
        return KAN_PLATFORM_SCAN_CODE_MUTE;
    case SDL_SCANCODE_VOLUMEUP:
        return KAN_PLATFORM_SCAN_CODE_VOLUME_UP;
    case SDL_SCANCODE_VOLUMEDOWN:
        return KAN_PLATFORM_SCAN_CODE_VOLUME_DOWN;
    case SDL_SCANCODE_KP_COMMA:
        return KAN_PLATFORM_SCAN_CODE_KEY_PAD_COMMA;
    case SDL_SCANCODE_KP_EQUALSAS400:
        return KAN_PLATFORM_SCAN_CODE_KEY_PAD_EQUALS_AS400;
    case SDL_SCANCODE_ALTERASE:
        return KAN_PLATFORM_SCAN_CODE_ALT_ERASE;
    case SDL_SCANCODE_SYSREQ:
        return KAN_PLATFORM_SCAN_CODE_SYS_REQ;
    case SDL_SCANCODE_CANCEL:
        return KAN_PLATFORM_SCAN_CODE_CANCEL;
    case SDL_SCANCODE_CLEAR:
        return KAN_PLATFORM_SCAN_CODE_CLEAR;
    case SDL_SCANCODE_PRIOR:
        return KAN_PLATFORM_SCAN_CODE_PRIOR;
    case SDL_SCANCODE_RETURN2:
        return KAN_PLATFORM_SCAN_CODE_RETURN_2;
    case SDL_SCANCODE_SEPARATOR:
        return KAN_PLATFORM_SCAN_CODE_SEPARATOR;
    case SDL_SCANCODE_OUT:
        return KAN_PLATFORM_SCAN_CODE_OUT;
    case SDL_SCANCODE_OPER:
        return KAN_PLATFORM_SCAN_CODE_OPER;
    case SDL_SCANCODE_CLEARAGAIN:
        return KAN_PLATFORM_SCAN_CODE_CLEAR_AGAIN;
    case SDL_SCANCODE_CRSEL:
        return KAN_PLATFORM_SCAN_CODE_CR_SEL;
    case SDL_SCANCODE_EXSEL:
        return KAN_PLATFORM_SCAN_CODE_EX_SEL;
    case SDL_SCANCODE_KP_00:
        return KAN_PLATFORM_SCAN_CODE_KEY_PAD_00;
    case SDL_SCANCODE_KP_000:
        return KAN_PLATFORM_SCAN_CODE_KEY_PAD_000;
    case SDL_SCANCODE_THOUSANDSSEPARATOR:
        return KAN_PLATFORM_SCAN_CODE_THOUSANDS_SEPARATOR;
    case SDL_SCANCODE_DECIMALSEPARATOR:
        return KAN_PLATFORM_SCAN_CODE_DECIMAL_SEPARATOR;
    case SDL_SCANCODE_CURRENCYUNIT:
        return KAN_PLATFORM_SCAN_CODE_CURRENCY_UNIT;
    case SDL_SCANCODE_CURRENCYSUBUNIT:
        return KAN_PLATFORM_SCAN_CODE_CURRENCY_SUBUNIT;
    case SDL_SCANCODE_KP_LEFTPAREN:
        return KAN_PLATFORM_SCAN_CODE_KEY_PAD_LEFT_PAREN;
    case SDL_SCANCODE_KP_RIGHTPAREN:
        return KAN_PLATFORM_SCAN_CODE_KEY_PAD_RIGHT_PAREN;
    case SDL_SCANCODE_KP_LEFTBRACE:
        return KAN_PLATFORM_SCAN_CODE_KEY_PAD_LEFT_BRACE;
    case SDL_SCANCODE_KP_RIGHTBRACE:
        return KAN_PLATFORM_SCAN_CODE_KEY_PAD_RIGHT_BRACE;
    case SDL_SCANCODE_KP_TAB:
        return KAN_PLATFORM_SCAN_CODE_KEY_PAD_TAB;
    case SDL_SCANCODE_KP_BACKSPACE:
        return KAN_PLATFORM_SCAN_CODE_KEY_PAD_BACKSPACE;
    case SDL_SCANCODE_KP_A:
        return KAN_PLATFORM_SCAN_CODE_KEY_PAD_A;
    case SDL_SCANCODE_KP_B:
        return KAN_PLATFORM_SCAN_CODE_KEY_PAD_B;
    case SDL_SCANCODE_KP_C:
        return KAN_PLATFORM_SCAN_CODE_KEY_PAD_C;
    case SDL_SCANCODE_KP_D:
        return KAN_PLATFORM_SCAN_CODE_KEY_PAD_D;
    case SDL_SCANCODE_KP_E:
        return KAN_PLATFORM_SCAN_CODE_KEY_PAD_E;
    case SDL_SCANCODE_KP_F:
        return KAN_PLATFORM_SCAN_CODE_KEY_PAD_F;
    case SDL_SCANCODE_KP_XOR:
        return KAN_PLATFORM_SCAN_CODE_KEY_PAD_XOR;
    case SDL_SCANCODE_KP_POWER:
        return KAN_PLATFORM_SCAN_CODE_KEY_PAD_POWER;
    case SDL_SCANCODE_KP_PERCENT:
        return KAN_PLATFORM_SCAN_CODE_KEY_PAD_PERCENT;
    case SDL_SCANCODE_KP_LESS:
        return KAN_PLATFORM_SCAN_CODE_KEY_PAD_LESS;
    case SDL_SCANCODE_KP_GREATER:
        return KAN_PLATFORM_SCAN_CODE_KEY_PAD_GREATER;
    case SDL_SCANCODE_KP_AMPERSAND:
        return KAN_PLATFORM_SCAN_CODE_KEY_PAD_AMPERSAND;
    case SDL_SCANCODE_KP_DBLAMPERSAND:
        return KAN_PLATFORM_SCAN_CODE_KEY_PAD_DOUBLE_AMPERSAND;
    case SDL_SCANCODE_KP_VERTICALBAR:
        return KAN_PLATFORM_SCAN_CODE_KEY_PAD_VERTICAL_BAR;
    case SDL_SCANCODE_KP_DBLVERTICALBAR:
        return KAN_PLATFORM_SCAN_CODE_KEY_PAD_DOUBLE_VERTICAL_BAR;
    case SDL_SCANCODE_KP_COLON:
        return KAN_PLATFORM_SCAN_CODE_KEY_PAD_COLON;
    case SDL_SCANCODE_KP_HASH:
        return KAN_PLATFORM_SCAN_CODE_KEY_PAD_HASH;
    case SDL_SCANCODE_KP_SPACE:
        return KAN_PLATFORM_SCAN_CODE_KEY_PAD_SPACE;
    case SDL_SCANCODE_KP_AT:
        return KAN_PLATFORM_SCAN_CODE_KEY_PAD_AT;
    case SDL_SCANCODE_KP_EXCLAM:
        return KAN_PLATFORM_SCAN_CODE_KEY_PAD_EXCLAMATION;
    case SDL_SCANCODE_KP_MEMSTORE:
        return KAN_PLATFORM_SCAN_CODE_KEY_PAD_MEM_STORE;
    case SDL_SCANCODE_KP_MEMRECALL:
        return KAN_PLATFORM_SCAN_CODE_KEY_PAD_MEM_RECALL;
    case SDL_SCANCODE_KP_MEMCLEAR:
        return KAN_PLATFORM_SCAN_CODE_KEY_PAD_MEM_CLEAR;
    case SDL_SCANCODE_KP_MEMADD:
        return KAN_PLATFORM_SCAN_CODE_KEY_PAD_MEM_ADD;
    case SDL_SCANCODE_KP_MEMSUBTRACT:
        return KAN_PLATFORM_SCAN_CODE_KEY_PAD_MEM_SUBTRACT;
    case SDL_SCANCODE_KP_MEMMULTIPLY:
        return KAN_PLATFORM_SCAN_CODE_KEY_PAD_MEM_MULTIPLY;
    case SDL_SCANCODE_KP_MEMDIVIDE:
        return KAN_PLATFORM_SCAN_CODE_KEY_PAD_MEM_DIVIDE;
    case SDL_SCANCODE_KP_PLUSMINUS:
        return KAN_PLATFORM_SCAN_CODE_KEY_PAD_PLUS_MINUS;
    case SDL_SCANCODE_KP_CLEAR:
        return KAN_PLATFORM_SCAN_CODE_KEY_PAD_CLEAR;
    case SDL_SCANCODE_KP_CLEARENTRY:
        return KAN_PLATFORM_SCAN_CODE_KEY_PAD_CLEAR_ENTRY;
    case SDL_SCANCODE_KP_BINARY:
        return KAN_PLATFORM_SCAN_CODE_KEY_PAD_BINARY;
    case SDL_SCANCODE_KP_OCTAL:
        return KAN_PLATFORM_SCAN_CODE_KEY_PAD_OCTAL;
    case SDL_SCANCODE_KP_DECIMAL:
        return KAN_PLATFORM_SCAN_CODE_KEY_PAD_DECIMAL;
    case SDL_SCANCODE_KP_HEXADECIMAL:
        return KAN_PLATFORM_SCAN_CODE_KEY_PAD_HEXADECIMAL;
    case SDL_SCANCODE_LCTRL:
        return KAN_PLATFORM_SCAN_CODE_LEFT_CONTROL;
    case SDL_SCANCODE_LSHIFT:
        return KAN_PLATFORM_SCAN_CODE_LEFT_SHIFT;
    case SDL_SCANCODE_LALT:
        return KAN_PLATFORM_SCAN_CODE_LEFT_ALT;
    case SDL_SCANCODE_LGUI:
        return KAN_PLATFORM_SCAN_CODE_LEFT_GUI;
    case SDL_SCANCODE_RCTRL:
        return KAN_PLATFORM_SCAN_CODE_RIGHT_CONTROL;
    case SDL_SCANCODE_RSHIFT:
        return KAN_PLATFORM_SCAN_CODE_RIGHT_SHIFT;
    case SDL_SCANCODE_RALT:
        return KAN_PLATFORM_SCAN_CODE_RIGHT_ALT;
    case SDL_SCANCODE_RGUI:
        return KAN_PLATFORM_SCAN_CODE_RIGHT_GUI;
    case SDL_SCANCODE_MODE:
        return KAN_PLATFORM_SCAN_CODE_MODE;
    case SDL_SCANCODE_MEDIA_NEXT_TRACK:
        return KAN_PLATFORM_SCAN_CODE_MEDIA_NEXT;
    case SDL_SCANCODE_MEDIA_PREVIOUS_TRACK:
        return KAN_PLATFORM_SCAN_CODE_MEDIA_PREVIOUS;
    case SDL_SCANCODE_MEDIA_STOP:
        return KAN_PLATFORM_SCAN_CODE_MEDIA_STOP;
    case SDL_SCANCODE_MEDIA_PLAY:
        return KAN_PLATFORM_SCAN_CODE_MEDIA_PLAY;
    case SDL_SCANCODE_MEDIA_SELECT:
        return KAN_PLATFORM_SCAN_CODE_MEDIA_SELECT;
    case SDL_SCANCODE_AC_SEARCH:
        return KAN_PLATFORM_SCAN_CODE_AC_SEARCH;
    case SDL_SCANCODE_AC_HOME:
        return KAN_PLATFORM_SCAN_CODE_AC_HOME;
    case SDL_SCANCODE_AC_BACK:
        return KAN_PLATFORM_SCAN_CODE_AC_BACK;
    case SDL_SCANCODE_AC_FORWARD:
        return KAN_PLATFORM_SCAN_CODE_AC_FORWARD;
    case SDL_SCANCODE_AC_STOP:
        return KAN_PLATFORM_SCAN_CODE_AC_STOP;
    case SDL_SCANCODE_AC_REFRESH:
        return KAN_PLATFORM_SCAN_CODE_AC_REFRESH;
    case SDL_SCANCODE_AC_BOOKMARKS:
        return KAN_PLATFORM_SCAN_CODE_AC_BOOKMARKS;
    case SDL_SCANCODE_MEDIA_EJECT:
        return KAN_PLATFORM_SCAN_CODE_EJECT;
    case SDL_SCANCODE_SLEEP:
        return KAN_PLATFORM_SCAN_CODE_SLEEP;
    case SDL_SCANCODE_MEDIA_REWIND:
        return KAN_PLATFORM_SCAN_CODE_MEDIA_REWIND;
    case SDL_SCANCODE_MEDIA_FAST_FORWARD:
        return KAN_PLATFORM_SCAN_CODE_MEDIA_FAST_FORWARD;
    case SDL_SCANCODE_SOFTLEFT:
        return KAN_PLATFORM_SCAN_CODE_SOFT_LEFT;
    case SDL_SCANCODE_SOFTRIGHT:
        return KAN_PLATFORM_SCAN_CODE_SOFT_RIGHT;
    case SDL_SCANCODE_CALL:
        return KAN_PLATFORM_SCAN_CODE_CALL;
    case SDL_SCANCODE_ENDCALL:
        return KAN_PLATFORM_SCAN_CODE_END_CALL;
    default:
        return KAN_PLATFORM_SCAN_CODE_UNKNOWN;
    }
}

enum kan_platform_modifier_mask_t to_kan_modifier_mask (SDL_Keymod modifiers)
{
    enum kan_platform_modifier_mask_t mask = 0u;

#define CHECK_MODIFIER(KAN_MODIFIER, SDL_MODIFIER)                                                                     \
    if (modifiers & SDL_MODIFIER)                                                                                      \
    {                                                                                                                  \
        mask |= KAN_MODIFIER;                                                                                          \
    }

    CHECK_MODIFIER (KAN_PLATFORM_MODIFIER_MASK_LEFT_SHIFT, SDL_KMOD_LSHIFT)
    CHECK_MODIFIER (KAN_PLATFORM_MODIFIER_MASK_RIGHT_SHIFT, SDL_KMOD_RSHIFT)
    CHECK_MODIFIER (KAN_PLATFORM_MODIFIER_MASK_LEFT_CONTROL, SDL_KMOD_LCTRL)
    CHECK_MODIFIER (KAN_PLATFORM_MODIFIER_MASK_RIGHT_CONTROL, SDL_KMOD_RCTRL)
    CHECK_MODIFIER (KAN_PLATFORM_MODIFIER_MASK_LEFT_ALT, SDL_KMOD_LALT)
    CHECK_MODIFIER (KAN_PLATFORM_MODIFIER_MASK_RIGHT_ALT, SDL_KMOD_RALT)
    CHECK_MODIFIER (KAN_PLATFORM_MODIFIER_MASK_LEFT_GUI, SDL_KMOD_LGUI)
    CHECK_MODIFIER (KAN_PLATFORM_MODIFIER_MASK_RIGHT_GUI, SDL_KMOD_RGUI)
    CHECK_MODIFIER (KAN_PLATFORM_MODIFIER_MASK_NUM_LOCK, SDL_KMOD_NUM)
    CHECK_MODIFIER (KAN_PLATFORM_MODIFIER_MASK_CAPS_LOCK, SDL_KMOD_CAPS)
    CHECK_MODIFIER (KAN_PLATFORM_MODIFIER_MASK_MODE, SDL_KMOD_MODE)
    CHECK_MODIFIER (KAN_PLATFORM_MODIFIER_MASK_SCROLL_LOCK, SDL_KMOD_SCROLL)
#undef CHECK_MODIFIER
    return mask;
}

enum kan_platform_mouse_button_t to_kan_mouse_button (uint8_t sdl_button)
{
    switch (sdl_button)
    {
    case SDL_BUTTON_LEFT:
        return KAN_PLATFORM_MOUSE_BUTTON_LEFT;
    case SDL_BUTTON_MIDDLE:
        return KAN_PLATFORM_MOUSE_BUTTON_MIDDLE;
    case SDL_BUTTON_RIGHT:
        return KAN_PLATFORM_MOUSE_BUTTON_RIGHT;
    case SDL_BUTTON_X1:
        return KAN_PLATFORM_MOUSE_BUTTON_X1;
    case SDL_BUTTON_X2:
        return KAN_PLATFORM_MOUSE_BUTTON_X2;
    }

    KAN_ASSERT (KAN_FALSE)
    return KAN_PLATFORM_MOUSE_BUTTON_LEFT;
}

enum kan_platform_pixel_format_t to_kan_pixel_format (SDL_PixelFormat pixel_format)
{
    switch (pixel_format)
    {
    case SDL_PIXELFORMAT_RGBA32:
        return KAN_PLATFORM_PIXEL_FORMAT_RGBA32;

    case SDL_PIXELFORMAT_ABGR32:
        return KAN_PLATFORM_PIXEL_FORMAT_ABGR32;

    case SDL_PIXELFORMAT_ARGB32:
        return KAN_PLATFORM_PIXEL_FORMAT_ARGB32;

    default:
        return KAN_PLATFORM_PIXEL_FORMAT_UNKNOWN;
    }
}

enum SDL_PixelFormat to_sdl_pixel_format (enum kan_platform_pixel_format_t pixel_format)
{
    switch (pixel_format)
    {
    case KAN_PLATFORM_PIXEL_FORMAT_UNKNOWN:
        return SDL_PIXELFORMAT_UNKNOWN;

    case KAN_PLATFORM_PIXEL_FORMAT_RGBA32:
        return SDL_PIXELFORMAT_RGBA32;

    case KAN_PLATFORM_PIXEL_FORMAT_ABGR32:
        return SDL_PIXELFORMAT_ABGR32;

    case KAN_PLATFORM_PIXEL_FORMAT_ARGB32:
        return SDL_PIXELFORMAT_ARGB32;
    }

    KAN_ASSERT (KAN_FALSE)
    return SDL_PIXELFORMAT_UNKNOWN;
}
