//! kan_resource_platform_configuration_entry_t

layer = default
data {
    __type = kan_resource_texture_platform_configuration_t
    supported_formats =
        KAN_RESOURCE_TEXTURE_FORMAT_UNCOMPRESSED_R8_SRGB,
        KAN_RESOURCE_TEXTURE_FORMAT_UNCOMPRESSED_RG16_SRGB,
        KAN_RESOURCE_TEXTURE_FORMAT_UNCOMPRESSED_RGBA32_SRGB,
        KAN_RESOURCE_TEXTURE_FORMAT_UNCOMPRESSED_R8_UNORM,
        KAN_RESOURCE_TEXTURE_FORMAT_UNCOMPRESSED_RG16_UNORM,
        KAN_RESOURCE_TEXTURE_FORMAT_UNCOMPRESSED_RGBA32_UNORM,
        KAN_RESOURCE_TEXTURE_FORMAT_UNCOMPRESSED_D16,
        KAN_RESOURCE_TEXTURE_FORMAT_UNCOMPRESSED_D32
}
