variables:
  GIT_SUBMODULE_STRATEGY: recursive
  GIT_SUBMODULE_DEPTH: 4

stages:
  - verify

build_and_test:
  stage: verify
  parallel:
    matrix:
      - PRESET:
          - debug_linux_gcc
          - debug_linux_gcc_x32
          - debug_linux_clang
          - sanitize_linux_clang
        SYSTEM_TAG: linux
        CONFIG: Debug
      - PRESET:
          - release_linux_gcc
          - release_linux_gcc_x32
          - release_linux_clang
        SYSTEM_TAG: linux
        CONFIG: Release
  tags:
    - $SYSTEM_TAG
  script:
    - cmake --preset $PRESET -B build/ci
    - cd build/ci
    - cmake --build . --target test_kan --config $CONFIG -j 6
    - ctest --build-config $CONFIG --parallel 6
