variables:
  GIT_SUBMODULE_STRATEGY: recursive
  GIT_SUBMODULE_DEPTH: 4

stages:
  - verify

build_and_test:
  stage: verify
  parallel:
    matrix:
      - PRESET:
          - debug_linux_gcc
          - debug_linux_gcc_x32
          - debug_linux_clang
        SYSTEM_TAG: linux
        CONFIG: Debug
      - PRESET: sanitize_linux_clang
        SYSTEM_TAG: linux
        CONFIG: Debug
        CTEST_FLAGS: -LE GRAPHICS
      - PRESET:
          - release_linux_gcc
          - release_linux_gcc_x32
          - release_linux_clang
        SYSTEM_TAG: linux
        CONFIG: Release
      - PRESET:
          - debug_windows_ninja_msvc
          - debug_windows_ninja_clang
        SYSTEM_TAG: windows
        CONFIG: Debug
        CTEST_FLAGS: -LE GRAPHICS
      - PRESET:
          - release_windows_ninja_msvc
          - release_windows_ninja_clang
        SYSTEM_TAG: windows
        CONFIG: Release
        CTEST_FLAGS: -LE GRAPHICS
  tags:
    - $SYSTEM_TAG
  script:
    - cmake --preset $PRESET -B build/ci
    - cd build/ci
    - cmake --build . --target kan_clang_format_fix --config $CONFIG
    - cmake --build . --target test_kan --config $CONFIG -j 5
    - ctest --build-config $CONFIG --parallel 5 -LE GRAPHICS
