name: format

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  check_format:
    defaults:
      run:
        shell: pwsh

    env:
      BUILD_DIRECTORY: ${{github.workspace}}/build

    runs-on: windows-2022
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Create build directory
        run: cmake -E make_directory ${{env.BUILD_DIRECTORY}}

      - name: Configure
        working-directory: ${{env.BUILD_DIRECTORY}}
        run: >
          cmake ${{github.workspace}} 
          -G "Visual Studio 17 2022" -A x64 -T clangcl
          -DKAN_FOR_FORMAT_ONLY=ON

      - name: Check
        working-directory: ${{env.BUILD_DIRECTORY}}
        run: cmake --build . --target kan_clang_format_check
